
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry txtName;

	private global::Gtk.Entry txtQuantity;

	private global::Gtk.Label lblName;

	private global::Gtk.Label lblQuantity;

	private global::Gtk.Label lblDescription;

	private global::Gtk.Label lblPrice;

	private global::Gtk.Button btnAdd;

	private global::Gtk.Button btnList;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txtList;

	private global::Gtk.Label lblList;

	private global::Gtk.Entry txtDescription;

	private global::Gtk.Entry txtPrice;

	private global::Gtk.Label lblCode;

	private global::Gtk.Entry txtCode;

	private global::Gtk.Button btnSearch;

	private global::Gtk.Button btnDelete;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtName = new global::Gtk.Entry();
		this.txtName.WidthRequest = 350;
		this.txtName.CanFocus = true;
		this.txtName.Name = "txtName";
		this.txtName.IsEditable = true;
		this.txtName.InvisibleChar = '•';
		this.fixed1.Add(this.txtName);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtName]));
		w1.X = 110;
		w1.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtQuantity = new global::Gtk.Entry();
		this.txtQuantity.WidthRequest = 120;
		this.txtQuantity.CanFocus = true;
		this.txtQuantity.Name = "txtQuantity";
		this.txtQuantity.IsEditable = true;
		this.txtQuantity.InvisibleChar = '•';
		this.fixed1.Add(this.txtQuantity);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtQuantity]));
		w2.X = 114;
		w2.Y = 132;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblName = new global::Gtk.Label();
		this.lblName.Name = "lblName";
		this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
		this.fixed1.Add(this.lblName);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblName]));
		w3.X = 45;
		w3.Y = 34;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblQuantity = new global::Gtk.Label();
		this.lblQuantity.Name = "lblQuantity";
		this.lblQuantity.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad:");
		this.fixed1.Add(this.lblQuantity);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblQuantity]));
		w4.X = 41;
		w4.Y = 142;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblDescription = new global::Gtk.Label();
		this.lblDescription.Name = "lblDescription";
		this.lblDescription.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion:");
		this.fixed1.Add(this.lblDescription);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblDescription]));
		w5.X = 24;
		w5.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblPrice = new global::Gtk.Label();
		this.lblPrice.Name = "lblPrice";
		this.lblPrice.LabelProp = global::Mono.Unix.Catalog.GetString("Costo:");
		this.fixed1.Add(this.lblPrice);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblPrice]));
		w6.X = 58;
		w6.Y = 199;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnAdd = new global::Gtk.Button();
		this.btnAdd.WidthRequest = 100;
		this.btnAdd.CanFocus = true;
		this.btnAdd.Name = "btnAdd";
		this.btnAdd.UseUnderline = true;
		this.btnAdd.Label = global::Mono.Unix.Catalog.GetString("Agregar");
		this.fixed1.Add(this.btnAdd);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAdd]));
		w7.X = 321;
		w7.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnList = new global::Gtk.Button();
		this.btnList.WidthRequest = 100;
		this.btnList.CanFocus = true;
		this.btnList.Name = "btnList";
		this.btnList.UseUnderline = true;
		this.btnList.Label = global::Mono.Unix.Catalog.GetString("Listar");
		this.fixed1.Add(this.btnList);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnList]));
		w8.X = 324;
		w8.Y = 189;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.HeightRequest = 350;
		this.vseparator1.Name = "vseparator1";
		this.fixed1.Add(this.vseparator1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vseparator1]));
		w9.X = 510;
		w9.Y = 3;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 350;
		this.GtkScrolledWindow.HeightRequest = 300;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtList = new global::Gtk.TextView();
		this.txtList.CanFocus = true;
		this.txtList.Name = "txtList";
		this.txtList.Editable = false;
		this.txtList.CursorVisible = false;
		this.GtkScrolledWindow.Add(this.txtList);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w11.X = 541;
		w11.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblList = new global::Gtk.Label();
		this.lblList.Name = "lblList";
		this.lblList.LabelProp = global::Mono.Unix.Catalog.GetString("Lista de Productos");
		this.fixed1.Add(this.lblList);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblList]));
		w12.X = 546;
		w12.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtDescription = new global::Gtk.Entry();
		this.txtDescription.WidthRequest = 350;
		this.txtDescription.CanFocus = true;
		this.txtDescription.Name = "txtDescription";
		this.txtDescription.IsEditable = true;
		this.txtDescription.InvisibleChar = '•';
		this.fixed1.Add(this.txtDescription);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtDescription]));
		w13.X = 109;
		w13.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtPrice = new global::Gtk.Entry();
		this.txtPrice.WidthRequest = 120;
		this.txtPrice.CanFocus = true;
		this.txtPrice.Name = "txtPrice";
		this.txtPrice.IsEditable = true;
		this.txtPrice.InvisibleChar = '•';
		this.fixed1.Add(this.txtPrice);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtPrice]));
		w14.X = 113;
		w14.Y = 187;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblCode = new global::Gtk.Label();
		this.lblCode.Name = "lblCode";
		this.lblCode.LabelProp = global::Mono.Unix.Catalog.GetString("Codigo:");
		this.fixed1.Add(this.lblCode);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblCode]));
		w15.X = 22;
		w15.Y = 287;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtCode = new global::Gtk.Entry();
		this.txtCode.WidthRequest = 200;
		this.txtCode.CanFocus = true;
		this.txtCode.Name = "txtCode";
		this.txtCode.IsEditable = true;
		this.txtCode.InvisibleChar = '•';
		this.fixed1.Add(this.txtCode);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCode]));
		w16.X = 79;
		w16.Y = 278;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSearch = new global::Gtk.Button();
		this.btnSearch.WidthRequest = 100;
		this.btnSearch.CanFocus = true;
		this.btnSearch.Name = "btnSearch";
		this.btnSearch.UseUnderline = true;
		this.btnSearch.Label = global::Mono.Unix.Catalog.GetString("Buscar");
		this.fixed1.Add(this.btnSearch);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSearch]));
		w17.X = 289;
		w17.Y = 279;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDelete = new global::Gtk.Button();
		this.btnDelete.WidthRequest = 100;
		this.btnDelete.CanFocus = true;
		this.btnDelete.Name = "btnDelete";
		this.btnDelete.UseUnderline = true;
		this.btnDelete.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
		this.fixed1.Add(this.btnDelete);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnDelete]));
		w18.X = 402;
		w18.Y = 280;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 922;
		this.DefaultHeight = 376;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnAdd.Clicked += new global::System.EventHandler(this.BtnAddClick);
		this.btnList.Clicked += new global::System.EventHandler(this.BtnListClick);
		this.btnSearch.Clicked += new global::System.EventHandler(this.BtnSearchClick);
		this.btnDelete.Clicked += new global::System.EventHandler(this.BtnDeleteClick);
	}
}
